[package]
name = "coconut-settings-panel"
version = "0.1.0"
edition = "2021"
description = "Coconut's settings window process"
license = "Apache-2.0"

[dependencies]
coconut-core = { path = "../core" }
creamui-core = { path = "../../../creamui/crates/core" }
creamui-image = { path = "../../../creamui/crates/image", features = ["webp", "jpeg"] }
creamui-jsx = { path = "../../../creamui/crates/jsx" }
creamui-macros = { path = "../../../creamui/crates/macros" }
creamui-reactive = { path = "../../../creamui/crates/reactive" }
creamui-render = { path = "../../../creamui/crates/render", features = ["platform-wayland"] }
creamui-theme = { path = "../../../creamui/crates/theme" }
creamui-widgets = { path = "../../../creamui/crates/widgets" }
