[package]
name = "creamshell-registry"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
creamshell-api = { path = "../api" }
creamshell-integration-mpris = { path = "../../integrations/mpris", optional = true }
creamshell-integration-upower = { path = "../../integrations/upower", optional = true }
creamshell-integration-bluez = { path = "../../integrations/bluez", optional = true }
creamshell-integration-brightnessctl = { path = "../../integrations/brightnessctl", optional = true }
creamshell-integration-network-manager = { path = "../../integrations/network-manager", optional = true }
creamshell-integration-power-profiles-daemon = { path = "../../integrations/power-profiles-daemon", optional = true }
creamshell-integration-pipewire = { path = "../../integrations/pipewire", optional = true }
creamshell-integration-kwin = { path = "../../integrations/kwin", optional = true }
creamshell-integration-windows = { path = "../../integrations/windows", optional = true }

[features]
default = [
    "mpris",
    "upower",
    "bluez",
    "brightnessctl",
    "network-manager",
    "power-profiles-daemon",
    "pipewire",
    "kwin",
]
mpris = ["dep:creamshell-integration-mpris"]
upower = ["dep:creamshell-integration-upower"]
bluez = ["dep:creamshell-integration-bluez"]
brightnessctl = ["dep:creamshell-integration-brightnessctl"]
network-manager = ["dep:creamshell-integration-network-manager"]
power-profiles-daemon = ["dep:creamshell-integration-power-profiles-daemon"]
pipewire = ["dep:creamshell-integration-pipewire"]
kwin = ["dep:creamshell-integration-kwin"]
windows = ["dep:creamshell-integration-windows"]
